name: ChestLocker
version: '${project.version}'
main: me.trobanko.chestlocker.ChestLocker
api-version: 1.18
authors: [ Trobanko ]
description: A chest locking plugin
commands:
  locker:
    description: Lock chests